use super::{assert_eq, *};

test_basic!(npc_, Npc,
    values_object_flags:flags,
    values_string:name,
    values_string:script,
    values_string:mesh,
    values_inventory:inventory,
    values_spells:spells,
    values_i16:ai_data:hello,
    values_i8:ai_data:fight,
    values_i8:ai_data:flee,
    values_i8:ai_data:alarm,
    values_service_flags:ai_data:services,
    values_ai_packages_wander:ai_packages,
    values_travel_destinations_i:travel_destinations,
    values_string:race,
    values_string:class,
    values_string:faction,
    values_string:head,
    values_string:hair,
    values_npc_flags:npc_flags,
    values_u8:blood_type,
    values_i16:data:level,
    values_some_npc_data_skills_attributes:data:stats,
    values_i8:data:disposition,
    values_i8:data:reputation,
    values_i8:data:rank,
    values_u32:data:gold
);
